### ISSUE TITLE
Linux install problems

### ISSUE THREAD

**Issue by 8lobbo** [PreMiD/PreMiD#183]
I'm not the most "Linux smarts" person, explaining how to fix this like i'm 5 years old or something would be great(tm)

OS: Duzeru, based on Debian 9.

I don't know if this has already happened to anyone else but, trying to install gives me this:
```
   smolyoshino@sakura-challenge   ~/Documents/PreMiD/src   stable  npm install
npm WARN discord-rpc@3.0.1 requires a peer of register-scheme@github:devsnek/node-register-scheme but none is installed. You must install peer dependencies yourself.
npm WARN premid@1.2.0 No repository field.

audited 4385 packages in 8.162s
found 221 vulnerabilities (3 low, 6 moderate, 211 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
   smolyoshino@sakura-challenge   ~/Documents/PreMiD/src   stable  sudo npm audit fix
npm WARN discord-rpc@3.0.1 requires a peer of register-scheme@github:devsnek/node-register-scheme but none is installed. You must install peer dependencies yourself.
npm WARN premid@1.2.0 No repository field.

updated 1 package in 6.328s
fixed 208 of 221 vulnerabilities in 4385 scanned packages
  13 vulnerabilities required manual review and could not be updated
```
and, later trying to run it, this happens: 
```
   smolyoshino@sakura-challenge   ~/Documents/PreMiD/src   stable  npm start

> premid@1.2.0 start /home/smolyoshino/Documents/PreMiD/src
> electron .

(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
App threw an error during load
Error: Cannot find module 'aws4'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/smolyoshino/Documents/PreMiD/src/node_modules/electron-prebuilt-compile/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)npm start

> premid@1.2.0 start /home/smolyoshino/Documents/PreMiD/src
> electron .

(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
(electron) The 'lstatSyncNoException' function has been deprecated and marked for removal.
App threw an error during load
Error: Cannot find module 'aws4'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/smolyoshino/Documents/PreMiD/src/node_modules/electron-prebuilt-compile/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/smolyoshino/Documents/PreMiD/src/node_modules/request/request.js:10:12)
    at Object.<anonymous> (/home/smolyoshino/Documents/PreMiD/src/node_modules/request/request.js:1553:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.require.extensions.(anonymous function) [as .js] (/home/smolyoshino/Documents/PreMiD/src/node_modules/electron-compile/lib/require-hook.js:77:14)
    at Module.load (internal/modules/cjs/loader.js:620:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'aws4'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/smolyoshino/Documents/PreMiD/src/node_modules/electron-prebuilt-compile/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/smolyoshino/Documents/PreMiD/src/node_modules/request/request.js:10:12)
    at Object.<anonymous> (/home/smolyoshino/Documents/PreMiD/src/node_modules/request/request.js:1553:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.require.extensions.(anonymous function) [as .js] (/home/smolyoshino/Documents/PreMiD/src/node_modules/electron-compile/lib/require-hook.js:77:14)
    at Module.load (internal/modules/cjs/loader.js:620:32)

```

**Comment by 8lobbo** [comment]
edit: fixed it after asking some people some stuff, but still wouldnt hurt if anyone has an explanation of what went wrong for someone else
